apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: ingress-nginx
  namespace: charts
  labels:
    argocd.argoproj.io/instance: auto-resources
spec:
  interval: 30m
  url: https://kubernetes.github.io/ingress-nginx