---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: releases
  namespace: wego-system
spec:
  interval: 1m0s
  path: ./releases
  prune: true
  sourceRef:
    kind: GitRepository
    name: releases

