---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: wego-auto-github-testigops
  namespace: wego-system
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/mtparet/testigops.git

