apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: wego-example
  namespace: wego-system
resources:
- app.yaml
- wego-example-gitops-deploy.yaml
- wego-example-gitops-source.yaml
