---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
  labels:
    argocd.argoproj.io/instance: auto-resources
spec:
  interval: 60m
  releaseName: cert-manager
  chart:
    spec:
      chart: cert-manager
      version: v1.6.1
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: charts
  values:
    installCRDs: true
    securityContext:
      fsGroup: 1000
      runAsUser: 1000
      runAsNonRoot: true
