apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: elastic-operator
  namespace: elastic-system
  labels:
    argocd.argoproj.io/instance: auto-resources
spec:
  interval: 60m
  releaseName: elastic-operator
  chart:
    spec:
      chart: eck-operator
      version: "1.8.0"
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: charts